platform :ios, '7.0'
target :TLChat do
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.4'
pod 'Masonry', '~> 0.6.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0-beta4'
pod 'MJExtension', '~> 3.0.10'
pod 'FMDB', '~> 2.6'
pod 'UMengAnalytics', '~> 3.6.6'
pod 'ReactiveCocoa', '~> 2.5' 
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'MWPhotoBrowser', '~> 2.1.1'
end
